version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:7.0.4
    restart: unless-stopped
    networks:
      pritunl:
        ipv4_address: 172.172.172.2
    ports:
      - "27017:27017"
    volumes:
      -  ./runtime/mongo/db:/data/db
  pritunl:
    container_name: pritunl
    build:
      context: .
      dockerfile: builder/pritunl/Dockerfile
    image: pritunl
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      pritunl:
        ipv4_address: 172.172.172.1
    ports:
      - "12281:80"
      - "12282:443"
      - "15414:15414/udp"
    privileged: true
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    networks:
      pritunl:
        ipv4_address: 172.172.172.3
    ports:
#      - "53:53/tcp" # plain DNS.
#      - "53:53/udp"
#     - "67:67/udp" #add if you intend to use AdGuard Home as a DHCP server.
#      - "68:68"
#      - "80:80/tcp" #add if you are going to use AdGuard Home's admin panel as well as run AdGuard Home as an HTTPS/DNS-over-HTTPS server.
#      - "443:443"
      - "3000:3000/tcp" # first install webgui
      - "12280:80" # DASHBOARD
#      - "853:853/tcp" #add if you are going to run AdGuard Home as a DNS-over-TLS server.
#      - "784:784/udp"
#      - "853:853/udp"
#      - "8853:8853/udp" #add if you are going to run AdGuard Home as a DNS-over-QUIC server. You may only leave one or two of these
#      - "5443:5443" #add if you are going to run AdGuard Home as a DNSCrypt server.
    volumes:
      - ./runtime/adguardhome/work:/opt/adguardhome/work
      - ./runtime/adguardhome/conf:/opt/adguardhome/conf
    privileged: true
networks:
  pritunl:
    ipam:
      config:
        - subnet: 172.172.172.0/16