services:
  xui:
    container_name: x-ui
    image: enwaiax/x-ui:latest
    restart: unless-stopped
    privileged: true
    networks:
      pritunl:
        ipv4_address: 172.172.172.6
    ports:
      - "54321:54321"
      - "443:443"
    volumes:
      - ./runtime/xui/db/:/etc/x-ui/
      - ./runtime/xui/cert/:/root/cert/

  ikev2:
    image: hwdsl2/ipsec-vpn-server:latest
    container_name: ikev2-vpn
    privileged: true
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    volumes:
      - ./runtime/ikev2/data:/etc/ipsec.d
      - ./runtime/ikev2/lib/modules:/lib/modules:ro
    env_file:
      - ikev2.env

  # strongman:
  #   image: ghcr.io/kennethkoffi/strongman:latest
  #   build:
  #     context: .
  #     dockerfile: builder/strongman/Dockerfile
  #   container_name: strongman-ui
  #   ports:
  #     - "1515:1515"
  #   volumes:
  #     - ./runtime/ikev2/data:/etc/ipsec.d
  #   env_file:
  #     - strongman.env
  #   depends_on:
  #     - ikev2

  pritunl:
    container_name: pritunl
    image: ghcr.io/jippi/docker-pritunl
    restart: unless-stopped
    privileged: true
    dns:
      - 172.172.172.3
    depends_on:
      - mongo
    networks:
      pritunl:
        ipv4_address: 172.172.172.1
    environment:
      - PRITUNL_MONGODB_URI=mongodb://mongo:27017/pritunl
    ports:
      - "12281:80"
      - "12282:443"
      - "10150:10150/udp" #openvpn
      - "10151:10151/udp" #wireguard
    volumes:
      - './runtime/pritunl/etc:/etc/pritunl'
      - './runtime/pritunl/lib:/var/lib/pritunl'
      - './runtime/pritunl/mongodb:/var/lib/mongodb'

  wireguard:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wireguard
    volumes:
      - ./runtime/wireguard/etc:/etc/wireguard
      - ./runtime/wireguard/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "12283:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    networks:
      pritunl:
        ipv4_address: 172.172.172.3
    ports:
      #      - "53:53/tcp" # plain DNS.
      #      - "53:53/udp"
      #     - "67:67/udp" #add if you intend to use AdGuard Home as a DHCP server.
      #      - "68:68"
      #      - "80:80/tcp" #add if you are going to use AdGuard Home's admin panel as well as run AdGuard Home as an HTTPS/DNS-over-HTTPS server.
      #      - "443:443"
      - "3000:3000/tcp" # first install webgui
      - "12280:80" # DASHBOARD
    #      - "853:853/tcp" #add if you are going to run AdGuard Home as a DNS-over-TLS server.
    #      - "784:784/udp"
    #      - "853:853/udp"
    #      - "8853:8853/udp" #add if you are going to run AdGuard Home as a DNS-over-QUIC server. You may only leave one or two of these
    #      - "5443:5443" #add if you are going to run AdGuard Home as a DNSCrypt server.
    volumes:
      - ./runtime/adguardhome/work:/opt/adguardhome/work
      - ./runtime/adguardhome/conf:/opt/adguardhome/conf
    privileged: true

  mongo:
    container_name: mongo
    image: mongo:4
    restart: unless-stopped
    networks:
      pritunl:
        ipv4_address: 172.172.172.2
    ports:
      - "27017:27017"
    volumes:
      -  ./runtime/mongo/db:/data/db

  cloudreve:
    image: cloudreve/cloudreve:latest
    container_name: cloudreve-backend
    depends_on:
      - redis
    restart: always
    ports:
      - "5212:5212"
    environment:
      - CR_CONF_Database.Type=sqlite
      - CR_CONF_Redis.Server=redis:6379
    networks:
      pritunl:
    volumes:
      - ./runtime/cloudreve/data:/cloudreve/data

  redis:
    image: redis:latest
    container_name: redis
    networks:
      pritunl:
    volumes:
      - ./runtime/redis/data:/data

networks:
  pritunl:
    ipam:
      config:
        - subnet: 172.172.0.0/16