version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:7.0.4
    networks:
      - pritunl
    ports:
      - "27017:27017"
    restart: always
    volumes:
      -  ./db:/data/db
  pritunl:
    container_name: pritunl
    build:
      context: .
      dockerfile: Dockerfile
    image: pritunl
    depends_on:
      - mongo
    networks:
      - pritunl
    ports:
      - "80:80"
      - "443:443"
      - "15414:15414/udp"
    privileged: true
    restart: always

networks:
  pritunl: